trigger:
    - master

pool:
    vmImage: 'ubuntu-latest'

steps:

- script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly-2020-01-30
  displayName: 'Install rustup toolchain'

- script: |
    curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  displayName: 'Install wasm-pack'

- script: |
        rustup override set nightly-2020-01-30
  displayName: 'Override wasm-pack default toolchain'

- script: sudo npm i -g lerna
  displayName: 'Install lerna'

- script: lerna bootstrap
  displayName: 'Run lerna bootstrap'

- script: lerna run build
  displayName: 'Run lerna build'
  
- script: |
    git checkout master  
    echo "//registry.npmjs.org/:_authToken=$(NPM_TOKEN)" > ~/.npmrc
    lerna publish --yes
  displayName: 'Run lerna publish'
