declare module 'crypto-key-composer' {
/** Declaration file generated by dts-gen */

export function composePrivateKey(decomposedKey: any, options: any): void;

export function composePublicKey(decomposedKey: any): void;

export function decomposePrivateKey(inputKey: any, options: any): void;

export function decomposePublicKey(inputKey: any, options: any): void;

export function getKeyTypeFromAlgorithm(keyAlgorithm: any): any;

}
