/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Catalyst.Protocol.Deltas.Delta');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Catalyst.Protocol.Transaction.CFTransactionEntry');
goog.require('proto.Catalyst.Protocol.Transaction.CoinbaseEntry');
goog.require('proto.Catalyst.Protocol.Transaction.STTransactionEntry');
goog.require('proto.google.protobuf.Timestamp');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Catalyst.Protocol.Deltas.Delta = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Catalyst.Protocol.Deltas.Delta.repeatedFields_, null);
};
goog.inherits(proto.Catalyst.Protocol.Deltas.Delta, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Catalyst.Protocol.Deltas.Delta.displayName = 'proto.Catalyst.Protocol.Deltas.Delta';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Catalyst.Protocol.Deltas.Delta.repeatedFields_ = [6,7,8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.toObject = function(opt_includeInstance) {
  return proto.Catalyst.Protocol.Deltas.Delta.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Catalyst.Protocol.Deltas.Delta} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Catalyst.Protocol.Deltas.Delta.toObject = function(includeInstance, msg) {
  var f, obj = {
    version: jspb.Message.getFieldWithDefault(msg, 1, 0),
    previousdeltadfshash: msg.getPreviousdeltadfshash_asB64(),
    merkleroot: msg.getMerkleroot_asB64(),
    merklepoda: msg.getMerklepoda_asB64(),
    timestamp: (f = msg.getTimestamp()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f),
    stentriesList: jspb.Message.toObjectList(msg.getStentriesList(),
    proto.Catalyst.Protocol.Transaction.STTransactionEntry.toObject, includeInstance),
    cfentriesList: jspb.Message.toObjectList(msg.getCfentriesList(),
    proto.Catalyst.Protocol.Transaction.CFTransactionEntry.toObject, includeInstance),
    cbentriesList: jspb.Message.toObjectList(msg.getCbentriesList(),
    proto.Catalyst.Protocol.Transaction.CoinbaseEntry.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Catalyst.Protocol.Deltas.Delta}
 */
proto.Catalyst.Protocol.Deltas.Delta.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Catalyst.Protocol.Deltas.Delta;
  return proto.Catalyst.Protocol.Deltas.Delta.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Catalyst.Protocol.Deltas.Delta} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Catalyst.Protocol.Deltas.Delta}
 */
proto.Catalyst.Protocol.Deltas.Delta.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVersion(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPreviousdeltadfshash(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setMerkleroot(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setMerklepoda(value);
      break;
    case 5:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 6:
      var value = new proto.Catalyst.Protocol.Transaction.STTransactionEntry;
      reader.readMessage(value,proto.Catalyst.Protocol.Transaction.STTransactionEntry.deserializeBinaryFromReader);
      msg.addStentries(value);
      break;
    case 7:
      var value = new proto.Catalyst.Protocol.Transaction.CFTransactionEntry;
      reader.readMessage(value,proto.Catalyst.Protocol.Transaction.CFTransactionEntry.deserializeBinaryFromReader);
      msg.addCfentries(value);
      break;
    case 8:
      var value = new proto.Catalyst.Protocol.Transaction.CoinbaseEntry;
      reader.readMessage(value,proto.Catalyst.Protocol.Transaction.CoinbaseEntry.deserializeBinaryFromReader);
      msg.addCbentries(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Catalyst.Protocol.Deltas.Delta.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Catalyst.Protocol.Deltas.Delta} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Catalyst.Protocol.Deltas.Delta.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVersion();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getPreviousdeltadfshash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getMerkleroot_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getMerklepoda_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getStentriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.Catalyst.Protocol.Transaction.STTransactionEntry.serializeBinaryToWriter
    );
  }
  f = message.getCfentriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.Catalyst.Protocol.Transaction.CFTransactionEntry.serializeBinaryToWriter
    );
  }
  f = message.getCbentriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      proto.Catalyst.Protocol.Transaction.CoinbaseEntry.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 Version = 1;
 * @return {number}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.Catalyst.Protocol.Deltas.Delta.prototype.setVersion = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bytes PreviousDeltaDfsHash = 2;
 * @return {string}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.getPreviousdeltadfshash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes PreviousDeltaDfsHash = 2;
 * This is a type-conversion wrapper around `getPreviousdeltadfshash()`
 * @return {string}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.getPreviousdeltadfshash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPreviousdeltadfshash()));
};


/**
 * optional bytes PreviousDeltaDfsHash = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPreviousdeltadfshash()`
 * @return {!Uint8Array}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.getPreviousdeltadfshash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPreviousdeltadfshash()));
};


/** @param {!(string|Uint8Array)} value */
proto.Catalyst.Protocol.Deltas.Delta.prototype.setPreviousdeltadfshash = function(value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes MerkleRoot = 3;
 * @return {string}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.getMerkleroot = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes MerkleRoot = 3;
 * This is a type-conversion wrapper around `getMerkleroot()`
 * @return {string}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.getMerkleroot_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getMerkleroot()));
};


/**
 * optional bytes MerkleRoot = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getMerkleroot()`
 * @return {!Uint8Array}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.getMerkleroot_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getMerkleroot()));
};


/** @param {!(string|Uint8Array)} value */
proto.Catalyst.Protocol.Deltas.Delta.prototype.setMerkleroot = function(value) {
  jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional bytes MerklePoda = 4;
 * @return {string}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.getMerklepoda = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes MerklePoda = 4;
 * This is a type-conversion wrapper around `getMerklepoda()`
 * @return {string}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.getMerklepoda_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getMerklepoda()));
};


/**
 * optional bytes MerklePoda = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getMerklepoda()`
 * @return {!Uint8Array}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.getMerklepoda_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getMerklepoda()));
};


/** @param {!(string|Uint8Array)} value */
proto.Catalyst.Protocol.Deltas.Delta.prototype.setMerklepoda = function(value) {
  jspb.Message.setProto3BytesField(this, 4, value);
};


/**
 * optional google.protobuf.Timestamp TimeStamp = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 5));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.Catalyst.Protocol.Deltas.Delta.prototype.setTimestamp = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.Catalyst.Protocol.Deltas.Delta.prototype.clearTimestamp = function() {
  this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * repeated Catalyst.Protocol.Transaction.STTransactionEntry STEntries = 6;
 * @return {!Array<!proto.Catalyst.Protocol.Transaction.STTransactionEntry>}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.getStentriesList = function() {
  return /** @type{!Array<!proto.Catalyst.Protocol.Transaction.STTransactionEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Catalyst.Protocol.Transaction.STTransactionEntry, 6));
};


/** @param {!Array<!proto.Catalyst.Protocol.Transaction.STTransactionEntry>} value */
proto.Catalyst.Protocol.Deltas.Delta.prototype.setStentriesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.Catalyst.Protocol.Transaction.STTransactionEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Catalyst.Protocol.Transaction.STTransactionEntry}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.addStentries = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.Catalyst.Protocol.Transaction.STTransactionEntry, opt_index);
};


proto.Catalyst.Protocol.Deltas.Delta.prototype.clearStentriesList = function() {
  this.setStentriesList([]);
};


/**
 * repeated Catalyst.Protocol.Transaction.CFTransactionEntry CFEntries = 7;
 * @return {!Array<!proto.Catalyst.Protocol.Transaction.CFTransactionEntry>}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.getCfentriesList = function() {
  return /** @type{!Array<!proto.Catalyst.Protocol.Transaction.CFTransactionEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Catalyst.Protocol.Transaction.CFTransactionEntry, 7));
};


/** @param {!Array<!proto.Catalyst.Protocol.Transaction.CFTransactionEntry>} value */
proto.Catalyst.Protocol.Deltas.Delta.prototype.setCfentriesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.Catalyst.Protocol.Transaction.CFTransactionEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Catalyst.Protocol.Transaction.CFTransactionEntry}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.addCfentries = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.Catalyst.Protocol.Transaction.CFTransactionEntry, opt_index);
};


proto.Catalyst.Protocol.Deltas.Delta.prototype.clearCfentriesList = function() {
  this.setCfentriesList([]);
};


/**
 * repeated Catalyst.Protocol.Transaction.CoinbaseEntry CBEntries = 8;
 * @return {!Array<!proto.Catalyst.Protocol.Transaction.CoinbaseEntry>}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.getCbentriesList = function() {
  return /** @type{!Array<!proto.Catalyst.Protocol.Transaction.CoinbaseEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Catalyst.Protocol.Transaction.CoinbaseEntry, 8));
};


/** @param {!Array<!proto.Catalyst.Protocol.Transaction.CoinbaseEntry>} value */
proto.Catalyst.Protocol.Deltas.Delta.prototype.setCbentriesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.Catalyst.Protocol.Transaction.CoinbaseEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Catalyst.Protocol.Transaction.CoinbaseEntry}
 */
proto.Catalyst.Protocol.Deltas.Delta.prototype.addCbentries = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.Catalyst.Protocol.Transaction.CoinbaseEntry, opt_index);
};


proto.Catalyst.Protocol.Deltas.Delta.prototype.clearCbentriesList = function() {
  this.setCbentriesList([]);
};


