/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.displayName = 'proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    chunkid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    chunkbytes: msg.getChunkbytes_asB64(),
    correlationfilename: msg.getCorrelationfilename_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest}
 */
proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest;
  return proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest}
 */
proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setChunkid(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setChunkbytes(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setCorrelationfilename(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChunkid();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getChunkbytes_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getCorrelationfilename_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
};


/**
 * optional uint32 chunkId = 1;
 * @return {number}
 */
proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.prototype.getChunkid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.prototype.setChunkid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bytes chunkBytes = 2;
 * @return {string}
 */
proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.prototype.getChunkbytes = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes chunkBytes = 2;
 * This is a type-conversion wrapper around `getChunkbytes()`
 * @return {string}
 */
proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.prototype.getChunkbytes_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getChunkbytes()));
};


/**
 * optional bytes chunkBytes = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getChunkbytes()`
 * @return {!Uint8Array}
 */
proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.prototype.getChunkbytes_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getChunkbytes()));
};


/** @param {!(string|Uint8Array)} value */
proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.prototype.setChunkbytes = function(value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes correlationFileName = 3;
 * @return {string}
 */
proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.prototype.getCorrelationfilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes correlationFileName = 3;
 * This is a type-conversion wrapper around `getCorrelationfilename()`
 * @return {string}
 */
proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.prototype.getCorrelationfilename_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getCorrelationfilename()));
};


/**
 * optional bytes correlationFileName = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getCorrelationfilename()`
 * @return {!Uint8Array}
 */
proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.prototype.getCorrelationfilename_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getCorrelationfilename()));
};


/** @param {!(string|Uint8Array)} value */
proto.Catalyst.Protocol.Rpc.Node.TransferFileBytesRequest.prototype.setCorrelationfilename = function(value) {
  jspb.Message.setProto3BytesField(this, 3, value);
};


