/** Declaration file generated by dts-gen */
declare module 'libp2p-keychain' {
export = libp2p_keychain;

export interface KeyInfo {
    name: string;
    id: string;
}

declare class libp2p_keychain {
    constructor(...args: any[]);

    createKey(...args: any[]): void;

    exportKey(...args: any[]): string;

    findKeyById(...args: any[]): void;

    findKeyByName(...args: any[]): void;

    importKey(...args: any[]): Keyinfo;

    importPeer(...args: any[]): KeyInfo;

    listKeys(...args: any[]): void;

    removeKey(...args: any[]): void;

    renameKey(...args: any[]): void;

    static generateOptions(...args: any[]): void;

    static options: {
        dek: {
            hash: string;
            iterationCount: number;
            keyLength: number;
            salt: string;
        };
    };

}

};