# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
    - master

pool:
    vmImage: 'ubuntu-latest'

steps:
    - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly-2020-02-07
      displayName: 'Install rustup toolchain'

    - task: Npm@1
      displayName: 'Install NPM'
      inputs:
          command: 'install'

    - script: |
          rustup override set nightly
      displayName: 'Override wasm-pack default toolchain'

    - task: Npm@1
      displayName: 'Build node'
      inputs:
          command: 'custom'
          customCommand: 'run build:node'

    - task: Npm@1
      displayName: 'test node code'
      inputs:
          command: 'custom'
          customCommand: 'run test'

    - task: Npm@1
      displayName: 'wasm-pack test node'
      inputs:
          command: 'custom'
          customCommand: 'run test:cargo:node'

    - task: Npm@1
      displayName: 'wasm-pack test firefox'
      inputs:
          command: 'custom'
          customCommand: 'run test:cargo:firefox'

    - task: Npm@1
      displayName: 'wasm-pack test chrome'
      inputs:
          command: 'custom'
          customCommand: 'run test:cargo:chrome'
